import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { ResumeAnalysis, ScoreBreakdown } from '../types';

const DashboardPage: React.FC = () => {
  const [analysis, setAnalysis] = useState<ResumeAnalysis | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const result = sessionStorage.getItem('analysisResult');
    if (!result) {
      navigate('/');
      return;
    }
    
    try {
      setAnalysis(JSON.parse(result));
    } catch {
      navigate('/');
    }
  }, [navigate]);

  if (!analysis) {
    return (
      <div style={{ padding: '40px', textAlign: 'center', color: '#94A3B8' }}>
        Loading analysis...
      </div>
    );
  }

  const getScoreColor = (score: number) => {
    if (score >= 75) return '#10B981';
    if (score >= 50) return '#F59E0B';
    return '#EF4444';
  };

  const getScoreRingStyle = (score: number) => ({
    stroke: getScoreColor(score),
    strokeDasharray: '327',
    strokeDashoffset: 327 - (score / 100) * 327,
    strokeWidth: 8,
    fill: 'none',
    strokeLinecap: 'round' as const
  });

  return (
    <div style={{ padding: '40px 24px', maxWidth: '1400px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '40px', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <h1 style={{ fontSize: '28px', fontWeight: 800, color: '#F1F5F9', margin: 0 }}>
            Resume Analysis Report
          </h1>
          <p style={{ color: '#94A3B8', margin: '8px 0 0 0', fontSize: '16px' }}>
            Generated by Gemini AI on {new Date().toLocaleDateString()}
          </p>
        </div>
        <button 
          onClick={() => navigate('/')}
          style={{
            backgroundColor: 'transparent',
            border: '1px solid #1E1E2E',
            color: '#94A3B8',
            padding: '12px 24px',
            borderRadius: '10px',
            cursor: 'pointer',
            fontWeight: 500
          }}
        >
          ← Analyze Another
        </button>
      </div>

      {/* Metrics Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
        gap: '16px',
        marginBottom: '40px'
      }}>
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: '20px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '32px', fontWeight: 800, color: getScoreColor(analysis.score), marginBottom: '4px' }}>
            {Math.round(analysis.score)}
          </div>
          <div style={{ color: '#94A3B8', fontSize: '14px' }}>Overall Score</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: '20px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '32px', fontWeight: 800, color: '#6366F1' }}>
            {analysis.technicalSkills.length}
          </div>
          <div style={{ color: '#94A3B8', fontSize: '14px' }}>Tech Skills</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: '20px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '32px', fontWeight: 800, color: '#F59E0B' }}>
            {analysis.missingSkills.length}
          </div>
          <div style={{ color: '#94A3B8', fontSize: '14px' }}>Skill Gaps</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: '20px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '24px', fontWeight: 700, color: '#F1F5F9' }}>
            {analysis.experienceLevel}
          </div>
          <div style={{ color: '#94A3B8', fontSize: '14px' }}>Experience</div>
        </div>

        {analysis.matchPercentage !== null && (
          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '14px',
            padding: '20px',
            textAlign: 'center'
          }}>
            <div style={{ fontSize: '32px', fontWeight: 800, color: getScoreColor(analysis.matchPercentage) }}>
              {Math.round(analysis.matchPercentage)}%
            </div>
            <div style={{ color: '#94A3B8', fontSize: '14px' }}>JD Match</div>
          </div>
        )}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: '32px', marginBottom: '40px' }}>
        {/* Score Ring Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: '32px',
          textAlign: 'center'
        }}>
          <svg width="160" height="160" viewBox="0 0 160 160" style={{ marginBottom: '16px' }}>
            <circle 
              cx="80" 
              cy="80" 
              r="65" 
              fill="none" 
              stroke="#1E1E2E" 
              strokeWidth="12"
            />
            <circle 
              cx="80" 
              cy="80" 
              r="65" 
              style={getScoreRingStyle(analysis.score)}
            />
          </svg>
          <div style={{ fontSize: '36px', fontWeight: 800, color: getScoreColor(analysis.score), marginBottom: '8px' }}>
            {Math.round(analysis.score)}
          </div>
          <div style={{ fontSize: '14px', color: '#94A3B8' }}>Overall Score</div>
          <div style={{
            backgroundColor: 'rgba(99,102,241,0.15)',
            color: '#6366F1',
            padding: '4px 12px',
            borderRadius: '20px',
            fontSize: '12px',
            marginTop: '12px',
            display: 'inline-block'
          }}>
            AI Generated
          </div>
        </div>

        {/* Breakdown Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: '32px'
        }}>
          <h3 style={{ fontSize: '20px', fontWeight: 700, color: '#F1F5F9', marginBottom: '24px' }}>
            Score Breakdown
          </h3>
          
          {(['clarity', 'impact', 'skills', 'formatting'] as (keyof ScoreBreakdown)[]).map((key) => {
            const value = analysis.scoreBreakdown[key];
            const label = key.charAt(0).toUpperCase() + key.slice(1);
            const color = getScoreColor(value * 4); // Scale to 0-100
            
            return (
              <div key={key} style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '16px' }}>
                <div style={{ minWidth: '80px' }}>
                  <div style={{ fontSize: '24px', fontWeight: 700, color }}>{Math.round(value)}</div>
                  <div style={{ fontSize: '12px', color: '#94A3B8' }}>/25</div>
                </div>
                <div style={{ flex: 1, height: '12px', backgroundColor: '#1E1E2E', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ 
                    height: '100%', 
                    backgroundColor: color, 
                    borderRadius: '6px', 
                    width: `${(value / 25) * 100}%`,
                    transition: 'width 0.3s ease'
                  }} />
                </div>
                <div style={{ fontWeight: 500, color: '#F1F5F9', minWidth: '80px' }}>
                  {label}
                </div>
              </div>
            );
          })}

          <div style={{ marginTop: '24px', paddingTop: '24px', borderTop: '1px solid #2D2D3F' }}>
            <div style={{ color: '#94A3B8', fontSize: '14px', marginBottom: '12px' }}>AI Summary</div>
            <div style={{ lineHeight: 1.6, color: '#F1F5F9' }}>
              {analysis.summary}
            </div>
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }}>
        {/* Skills Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: '32px'
        }}>
          <h3 style={{ fontSize: '20px', fontWeight: 700, color: '#F1F5F9', marginBottom: '24px' }}>
            Skills Assessment
          </h3>
          
          <div style={{ marginBottom: '24px' }}>
            <div style={{ fontSize: '16px', fontWeight: 600, color: '#6366F1', marginBottom: '12px' }}>
              Technical Skills
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {analysis.technicalSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(99,102,241,0.15)',
                  color: '#6366F1',
                  padding: '6px 12px',
                  borderRadius: '20px',
                  fontSize: '14px',
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: '24px' }}>
            <div style={{ fontSize: '16px', fontWeight: 600, color: '#10B981', marginBottom: '12px' }}>
              Soft Skills
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {analysis.softSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(16,185,129,0.15)',
                  color: '#10B981',
                  padding: '6px 12px',
                  borderRadius: '20px',
                  fontSize: '14px',
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>

          <div>
            <div style={{ fontSize: '16px', fontWeight: 600, color: '#F59E0B', marginBottom: '12px' }}>
              Skills to Add
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {analysis.missingSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(245,158,11,0.15)',
                  color: '#F59E0B',
                  padding: '6px 12px',
                  borderRadius: '20px',
                  fontSize: '14px',
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Suggestions Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: '32px'
        }}>
          <div style={{ display: 'flex', gap: '24px', marginBottom: '24px', borderBottom: '1px solid #2D2D3F', paddingBottom: '24px' }}>
            <button style={{ flex: 1, padding: '12px', backgroundColor: 'rgba(99,102,241,0.15)', color: '#6366F1', border: 'none', borderRadius: '10px', fontWeight: 600 }}>Suggestions</button>
            <button style={{ flex: 1, padding: '12px', backgroundColor: 'transparent', color: '#94A3B8', border: 'none', borderRadius: '10px', fontWeight: 600 }}>Strengths</button>
          </div>

          <div>
            {analysis.suggestions.map((suggestion, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', marginBottom: '16px' }}>
                <div style={{
                  width: '24px',
                  height: '24px',
                  backgroundColor: '#6366F1',
                  color: 'white',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: '12px',
                  fontWeight: 700,
                  flexShrink: 0,
                  marginTop: '2px'
                }}>
                  {i + 1}
                </div>
                <div style={{ color: '#F1F5F9', lineHeight: 1.6 }}>
                  {suggestion}
                </div>
              </div>
            ))}
          </div>

          <div style={{ marginTop: '32px', paddingTop: '24px', borderTop: '1px solid #2D2D3F' }}>
            <div style={{ fontSize: '16px', fontWeight: 600, color: '#10B981', marginBottom: '16px' }}>
              Top Strengths
            </div>
            <ul style={{ listStyle: 'none', padding: 0 }}>
              {analysis.strengths.map((strength, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px', color: '#F1F5F9' }}>
                  <div style={{ 
                    width: '20px', 
                    height: '20px', 
                    backgroundColor: '#10B981', 
                    borderRadius: '50%', 
                    display: 'flex', 
                    alignItems: 'center', 
                    justifyContent: 'center',
                    fontSize: '12px',
                    color: 'white',
                    flexShrink: 0
                  }}>
                    ✓
                  </div>
                  <span style={{ lineHeight: 1.5 }}>{strength}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {analysis.matchPercentage !== null && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px', marginTop: '40px' }}>
          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '16px',
            padding: '32px'
          }}>
            <h3 style={{ fontSize: '20px', fontWeight: 700, color: '#F1F5F9', marginBottom: '24px' }}>
              Matched Keywords
            </h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {analysis.matchedKeywords.map((keyword, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(16,185,129,0.15)',
                  color: '#10B981',
                  padding: '6px 12px',
                  borderRadius: '20px',
                  fontSize: '14px'
                }}>
                  {keyword}
                </div>
              ))}
            </div>
          </div>

          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '16px',
            padding: '32px'
          }}>
            <h3 style={{ fontSize: '20px', fontWeight: 700, color: '#F1F5F9', marginBottom: '24px' }}>
              Missing Keywords
            </h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {analysis.missingKeywords.map((keyword, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(245,158,11,0.15)',
                  color: '#F59E0B',
                  padding: '6px 12px',
                  borderRadius: '20px',
                  fontSize: '14px'
                }}>
                  {keyword}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DashboardPage;
