import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { ResumeAnalysis, ScoreBreakdown } from '../types';

const DashboardPage: React.FC = () => {
  const [analysis, setAnalysis] = useState<ResumeAnalysis | null>(null);
  const [isMobile, setIsMobile] = useState(false)
  const navigate = useNavigate();

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768)
    checkMobile()
    window.addEventListener('resize', checkMobile)
    return () => window.removeEventListener('resize', checkMobile)
  }, [])

  useEffect(() => {
    const result = sessionStorage.getItem('analysisResult');
    if (!result) {
      navigate('/');
      return;
    }
    
    try {
      setAnalysis(JSON.parse(result));
    } catch {
      navigate('/');
    }
  }, [navigate]);

  if (!analysis) {
    return (
      <div style={{ padding: '40px', textAlign: 'center', color: '#94A3B8' }}>
        Loading analysis...
      </div>
    );
  }

  const getScoreColor = (score: number) => {
    if (score >= 75) return '#10B981';
    if (score >= 50) return '#F59E0B';
    return '#EF4444';
  };

  const getScoreRingStyle = (score: number) => ({
    stroke: getScoreColor(score),
    strokeDasharray: '327',
    strokeDashoffset: 327 - (score / 100) * 327,
    strokeWidth: 8,
    fill: 'none',
    strokeLinecap: 'round' as const
  });

  const gridColumns = isMobile ? '1fr' : 'repeat(auto-fit, minmax(160px, 1fr))'
  const metricsGap = isMobile ? '12px' : '16px'
  const cardPadding = isMobile ? '16px' : '20px'
  const sectionGap = isMobile ? '24px' : '32px'
  const mainGridCols = isMobile ? '1fr' : '280px 1fr'
  const twoColGrid = isMobile ? '1fr' : '1fr 1fr'
  const containerPadding = isMobile ? '24px 16px' : '40px 24px'
  const h1Size = isMobile ? '24px' : '28px'
  const h3Size = isMobile ? '18px' : '20px'
  const metricNumSize = isMobile ? '28px' : '32px'

  return (
    <div style={{ padding: containerPadding, maxWidth: '1400px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'flex-start', 
        marginBottom: sectionGap, 
        flexWrap: 'wrap', 
        gap: '16px' 
      }}>
        <div>
          <h1 style={{ fontSize: h1Size, fontWeight: 800, color: '#F1F5F9', margin: 0 }}>
            Resume Analysis Report
          </h1>
          <p style={{ color: '#94A3B8', margin: isMobile ? '4px 0 0 0' : '8px 0 0 0', fontSize: isMobile ? '14px' : '16px' }}>
            Generated by Gemini AI on {new Date().toLocaleDateString()}
          </p>
        </div>
        <button 
          onClick={() => navigate('/')}
          style={{
            backgroundColor: 'transparent',
            border: '1px solid #1E1E2E',
            color: '#94A3B8',
            padding: isMobile ? '10px 20px' : '12px 24px',
            borderRadius: '10px',
            cursor: 'pointer',
            fontWeight: 500,
            fontSize: isMobile ? '14px' : '14px',
            whiteSpace: 'nowrap'
          }}
        >
          ← Analyze Another
        </button>
      </div>

      {/* Metrics Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: gridColumns,
        gap: metricsGap,
        marginBottom: sectionGap
      }}>
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: cardPadding,
          textAlign: 'center'
        }}>
          <div style={{ fontSize: metricNumSize, fontWeight: 800, color: getScoreColor(analysis.score), marginBottom: '4px' }}>
            {Math.round(analysis.score)}
          </div>
          <div style={{ color: '#94A3B8', fontSize: isMobile ? '13px' : '14px' }}>Overall Score</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: cardPadding,
          textAlign: 'center'
        }}>
          <div style={{ fontSize: metricNumSize, fontWeight: 800, color: '#6366F1' }}>
            {analysis.technicalSkills.length}
          </div>
          <div style={{ color: '#94A3B8', fontSize: isMobile ? '13px' : '14px' }}>Tech Skills</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: cardPadding,
          textAlign: 'center'
        }}>
          <div style={{ fontSize: metricNumSize, fontWeight: 800, color: '#F59E0B' }}>
            {analysis.missingSkills.length}
          </div>
          <div style={{ color: '#94A3B8', fontSize: isMobile ? '13px' : '14px' }}>Skill Gaps</div>
        </div>

        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '14px',
          padding: cardPadding,
          textAlign: 'center'
        }}>
          <div style={{ fontSize: isMobile ? '22px' : '24px', fontWeight: 700, color: '#F1F5F9' }}>
            {analysis.experienceLevel}
          </div>
          <div style={{ color: '#94A3B8', fontSize: isMobile ? '13px' : '14px' }}>Experience</div>
        </div>

        {analysis.matchPercentage !== null && (
          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '14px',
            padding: cardPadding,
            textAlign: 'center'
          }}>
            <div style={{ fontSize: metricNumSize, fontWeight: 800, color: getScoreColor(analysis.matchPercentage) }}>
              {Math.round(analysis.matchPercentage)}%
            </div>
            <div style={{ color: '#94A3B8', fontSize: isMobile ? '13px' : '14px' }}>JD Match</div>
          </div>
        )}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: mainGridCols, gap: sectionGap, marginBottom: sectionGap }}>
        {/* Score Ring Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: isMobile ? '24px' : '32px',
          textAlign: 'center'
        }}>
          <svg width={isMobile ? "140" : "160"} height={isMobile ? "140" : "160"} viewBox="0 0 160 160" style={{ marginBottom: isMobile ? "12px" : "16px" }}>
            <circle 
              cx="80" 
              cy="80" 
              r="65" 
              fill="none" 
              stroke="#1E1E2E" 
              strokeWidth="12"
            />
            <circle 
              cx="80" 
              cy="80" 
              r="65" 
              style={getScoreRingStyle(analysis.score)}
            />
          </svg>
          <div style={{ fontSize: isMobile ? "32px" : "36px", fontWeight: 800, color: getScoreColor(analysis.score), marginBottom: isMobile ? "6px" : "8px" }}>
            {Math.round(analysis.score)}
          </div>
          <div style={{ fontSize: isMobile ? "13px" : "14px", color: '#94A3B8' }}>Overall Score</div>
          <div style={{
            backgroundColor: 'rgba(99,102,241,0.15)',
            color: '#6366F1',
            padding: isMobile ? '3px 10px' : '4px 12px',
            borderRadius: '20px',
            fontSize: isMobile ? "11px" : '12px',
            marginTop: isMobile ? "10px" : "12px",
            display: 'inline-block'
          }}>
            AI Generated
          </div>
        </div>

        {/* Breakdown Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: isMobile ? '24px' : '32px'
        }}>
          <h3 style={{ fontSize: isMobile ? "18px" : "20px", fontWeight: 700, color: '#F1F5F9', marginBottom: isMobile ? '20px' : '24px' }}>
            Score Breakdown
          </h3>
          
          {(['clarity', 'impact', 'skills', 'formatting'] as (keyof ScoreBreakdown)[]).map((key) => {
            const value = analysis.scoreBreakdown[key];
            const label = key.charAt(0).toUpperCase() + key.slice(1);
            const color = getScoreColor(value * 4); // Scale to 0-100
            
            return (
              <div key={key} style={{ display: 'flex', alignItems: 'center', gap: isMobile ? "12px" : "16px", marginBottom: isMobile ? "12px" : "16px" }}>
                <div style={{ minWidth: isMobile ? "70px" : "80px" }}>
                  <div style={{ fontSize: isMobile ? "20px" : "24px", fontWeight: 700, color }}>{Math.round(value)}</div>
                  <div style={{ fontSize: isMobile ? "11px" : "12px", color: '#94A3B8' }}>/25</div>
                </div>
                <div style={{ flex: 1, height: isMobile ? "10px" : "12px", backgroundColor: '#1E1E2E', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ 
                    height: '100%', 
                    backgroundColor: color, 
                    borderRadius: '6px', 
                    width: `${(value / 25) * 100}%`,
                    transition: 'width 0.3s ease'
                  }} />
                </div>
                <div style={{ fontWeight: 500, color: '#F1F5F9', minWidth: isMobile ? "70px" : "80px" }}>
                  {label}
                </div>
              </div>
            );
          })}

          <div style={{ marginTop: isMobile ? "20px" : "24px", paddingTop: isMobile ? "20px" : "24px", borderTop: '1px solid #2D2D3F' }}>
            <div style={{ color: '#94A3B8', fontSize: isMobile ? "13px" : "14px", marginBottom: isMobile ? "10px" : "12px" }}>AI Summary</div>
            <div style={{ lineHeight: 1.6, color: '#F1F5F9', fontSize: isMobile ? "14px" : "15px" }}>
              {analysis.summary}
            </div>
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: twoColGrid, gap: sectionGap }}>
        {/* Skills Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: isMobile ? '24px' : '32px'
        }}>
          <h3 style={{ fontSize: h3Size, fontWeight: 700, color: '#F1F5F9', marginBottom: isMobile ? '20px' : '24px' }}>
            Skills Assessment
          </h3>
          
          <div style={{ marginBottom: isMobile ? '20px' : '24px' }}>
            <div style={{ fontSize: isMobile ? "15px" : "16px", fontWeight: 600, color: '#6366F1', marginBottom: isMobile ? '10px' : "12px" }}>
              Technical Skills
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: isMobile ? "6px" : "8px" }}>
              {analysis.technicalSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(99,102,241,0.15)',
                  color: '#6366F1',
                  padding: isMobile ? '5px 10px' : '6px 12px',
                  borderRadius: '20px',
                  fontSize: isMobile ? "13px" : "14px",
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: isMobile ? '20px' : '24px' }}>
            <div style={{ fontSize: isMobile ? "15px" : "16px", fontWeight: 600, color: '#10B981', marginBottom: isMobile ? '10px' : "12px" }}>
              Soft Skills
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: isMobile ? "6px" : "8px" }}>
              {analysis.softSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(16,185,129,0.15)',
                  color: '#10B981',
                  padding: isMobile ? '5px 10px' : '6px 12px',
                  borderRadius: '20px',
                  fontSize: isMobile ? "13px" : "14px",
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>

          <div>
            <div style={{ fontSize: isMobile ? "15px" : "16px", fontWeight: 600, color: '#F59E0B', marginBottom: isMobile ? '10px' : "12px" }}>
              Skills to Add
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: isMobile ? "6px" : "8px" }}>
              {analysis.missingSkills.map((skill, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(245,158,11,0.15)',
                  color: '#F59E0B',
                  padding: isMobile ? '5px 10px' : '6px 12px',
                  borderRadius: '20px',
                  fontSize: isMobile ? "13px" : "14px",
                  fontWeight: 500
                }}>
                  {skill}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Suggestions Card */}
        <div style={{
          backgroundColor: '#12121A',
          border: '1px solid #1E1E2E',
          borderRadius: '16px',
          padding: isMobile ? '24px' : '32px'
        }}>
          <div style={{ 
            display: 'flex', 
            gap: isMobile ? '12px' : '24px', 
            marginBottom: isMobile ? '20px' : '24px', 
            borderBottom: '1px solid #2D2D3F', 
            paddingBottom: isMobile ? '20px' : '24px',
            flexDirection: isMobile ? 'column' : 'row'
          }}>
            <button style={{ flex: 1, padding: isMobile ? '10px' : '12px', backgroundColor: 'rgba(99,102,241,0.15)', color: '#6366F1', border: 'none', borderRadius: '10px', fontWeight: 600, fontSize: isMobile ? '14px' : '14px' }}>Suggestions</button>
            <button style={{ flex: 1, padding: isMobile ? '10px' : '12px', backgroundColor: 'transparent', color: '#94A3B8', border: 'none', borderRadius: '10px', fontWeight: 600, fontSize: isMobile ? '14px' : '14px' }}>Strengths</button>
          </div>

          <div>
            {analysis.suggestions.map((suggestion, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: isMobile ? "10px" : "12px", marginBottom: isMobile ? "12px" : "16px" }}>
                <div style={{
                  width: isMobile ? '20px' : '24px',
                  height: isMobile ? '20px' : '24px',
                  backgroundColor: '#6366F1',
                  color: 'white',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: isMobile ? '11px' : '12px',
                  fontWeight: 700,
                  flexShrink: 0,
                  marginTop: isMobile ? '1px' : '2px'
                }}>
                  {i + 1}
                </div>
                <div style={{ color: '#F1F5F9', lineHeight: 1.6, fontSize: isMobile ? '14px' : '15px' }}>
                  {suggestion}
                </div>
              </div>
            ))}
          </div>

          <div style={{ marginTop: isMobile ? '24px' : '32px', paddingTop: isMobile ? '20px' : '24px', borderTop: '1px solid #2D2D3F' }}>
            <div style={{ fontSize: isMobile ? '15px' : '16px', fontWeight: 600, color: '#10B981', marginBottom: isMobile ? '12px' : '16px' }}>
              Top Strengths
            </div>
            <ul style={{ listStyle: 'none', padding: 0 }}>
              {analysis.strengths.map((strength, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'center', gap: isMobile ? '10px' : '12px', marginBottom: isMobile ? '10px' : '12px', color: '#F1F5F9' }}>
                  <div style={{ 
                    width: isMobile ? '18px' : '20px', 
                    height: isMobile ? '18px' : '20px', 
                    backgroundColor: '#10B981', 
                    borderRadius: '50%', 
                    display: 'flex', 
                    alignItems: 'center', 
                    justifyContent: 'center',
                    fontSize: isMobile ? '11px' : '12px',
                    color: 'white',
                    flexShrink: 0
                  }}>
                    ✓
                  </div>
                  <span style={{ lineHeight: 1.5, fontSize: isMobile ? '14px' : '15px' }}>{strength}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {analysis.matchPercentage !== null && (
        <div style={{ display: 'grid', gridTemplateColumns: twoColGrid, gap: sectionGap, marginTop: '40px' }}>
          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '16px',
            padding: isMobile ? '24px' : '32px'
          }}>
            <h3 style={{ fontSize: h3Size, fontWeight: 700, color: '#F1F5F9', marginBottom: isMobile ? '20px' : '24px' }}>
              Matched Keywords
            </h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: isMobile ? "6px" : "8px" }}>
              {analysis.matchedKeywords.map((keyword, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(16,185,129,0.15)',
                  color: '#10B981',
                  padding: isMobile ? '5px 10px' : '6px 12px',
                  borderRadius: '20px',
                  fontSize: isMobile ? "13px" : "14px"
                }}>
                  {keyword}
                </div>
              ))}
            </div>
          </div>

          <div style={{
            backgroundColor: '#12121A',
            border: '1px solid #1E1E2E',
            borderRadius: '16px',
            padding: isMobile ? '24px' : '32px'
          }}>
            <h3 style={{ fontSize: h3Size, fontWeight: 700, color: '#F1F5F9', marginBottom: isMobile ? '20px' : '24px' }}>
              Missing Keywords
            </h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: isMobile ? "6px" : "8px" }}>
              {analysis.missingKeywords.map((keyword, i) => (
                <div key={i} style={{
                  backgroundColor: 'rgba(245,158,11,0.15)',
                  color: '#F59E0B',
                  padding: isMobile ? '5px 10px' : '6px 12px',
                  borderRadius: '20px',
                  fontSize: isMobile ? "13px" : "14px"
                }}>
                  {keyword}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DashboardPage;

